### ISSUE TITLE
Custom Line Types

### ISSUE THREAD

**Issue by bjclark13** [embiem/react-canvas-draw#10]
Hi! I really love this package, and its simplicity. 

I was wondering if you have done anything with custom lines, for example, rather than just a simple line, users can instead select from line types and choose to draw an arrow, or something to that effect.

If not, no worries, just checking. :)

**Comment by embiem** [comment]
Hi!

This component only supports free drawing. The only adjustable styles are the width and color of the brush for now.

**Comment by bjclark13** [comment]
Okay, thanks for getting back to me!
