### ISSUE TITLE
Question: Do you interested in adding fast load/redraw functionality?

### ISSUE THREAD

**Issue by AlexxxRu** [embiem/react-canvas-draw#103]
I need to change the color/radius for already drawn lines on the fly. For now, the `getSaveData/loadSavedData` functionality extremely slow. Mostly because it requires to draw each line on the tmp ctx and copy it to the drawing ctx. If you have 10+ lines (even with 3 points only) it will have a noticeable lag.

I've added a new method to redraw all lines with different colors/radius. So if you someone interested I'll be glad to open a PR.

**Comment by embiem** [comment]
I'm currently cleaning up this repo. Would be happy to review your PR if you still want to submit one.
