### ISSUE TITLE
onClick event

### ISSUE THREAD

**Issue by ziaongit** [embiem/react-canvas-draw#113]
How we can add onClick event to React Canvas Draw. It will be great if the user click on the can add mark.

**Comment by embiem** [comment]
`onClick` event is currently not supported. Could you please elaborate a bit more on what would be your use case for it?

**Comment by ziaongit** [comment]
![image](https://user-images.githubusercontent.com/6294965/140698571-41898c6c-16a7-4874-a542-cefce7389999.png)
If we have a click event then we can add notes to that. Click on the spot and add a note.
What I want to achieve is given in this example.

https://codepen.io/onur_kaplan/pen/XaWeNK

**Comment by embiem** [comment]
Ah I see. In my opinion this functionality should rather live outside of the react-canvas-draw component, like a wrapper that detects the clicks.  But I'm open for discussion on this, especially if other people would like to have this functionality built-in.
