### ISSUE TITLE
it seems it does not supports react 17+ versions?

### ISSUE THREAD

**Issue by jhaji2911** [embiem/react-canvas-draw#121]
npm ERR! While resolving: image-text-detector@0.1.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"16.x" from react-canvas-draw@1.1.1
npm ERR! node_modules/react-canvas-draw
npm ERR!   react-canvas-draw@"*" from the root project
npm ERR!

**Comment by daiyi** [comment]
Were you able to fix this? I'm running into the same issue.

**Comment by Talmaj** [comment]
Why did you close this? I also get this error. I installed it with `--legacy-peer-deps` flag to override it.
