### ISSUE TITLE
Cannot read properties of undefined (reading 'getPointerCoordinates') 

### ISSUE THREAD

**Issue by danhiel98** [embiem/react-canvas-draw#129]
That error appears when I use the library in a next js project hosted in Vercel.
I have noticed that today, because a few days ago it was working fine.

I don't know if it is due to the changes that have been made in the library or perhaps in Vercel.

**Comment by danhiel98** [comment]
I've already solve the problem.
What happened is that Vercel does not support the property `canvasWidth='100%'`

**Comment by sacru2red** [comment]
same Issue.
canvasHeight and canvasWidth can recive only number Value.
CanvasDraw.lazy is undefined When canvasWidth is '100%'
