### ISSUE TITLE
Warning: Invalid PropTypes for canvas dimensions

### ISSUE THREAD

**Issue by m0Rdk** [embiem/react-canvas-draw#15]
Greetings!

I have recently been using your package for a project at work, and say that I feel very comfortable with it. It's simple, reliable and predictible. Thank you very much.

I found that wherever I use a `string` to set percentage dimensions in `canvasWidth` or `canvasHeight` properties (which I have to), `PropTypes` throws a warning message telling me to set it as a `number` instead of a `string`. However, the component behaves as expected for the relative width and height, so I suppose it is using CSS `width` and `height` properties (which is fine up to this point).

This is the message:

![image](https://user-images.githubusercontent.com/16738837/54620649-c7294100-4a66-11e9-9f7e-6e1a36f128f6.png)

Although this is not a breaking issue, it is quite bothering to see a huge warning at the console every time the component is mounted. I think this would be easily fixed by supporting both `string` and `number` types for this two properties.

Just changing this:
```js
export default class extends PureComponent {
   static propTypes = {
      ...,
      canvasWidth: PropTypes.number,
      canvasHeight: PropTypes.number,
      ...
   }
   ...
}
```
to this:
```js
const dimensionsTypes = PropTypes.oneOfType([
   PropTypes.number,
   PropTypes.string
]);

export default class extends PureComponent {
   static propTypes = {
      ...,
      canvasWidth: dimensionsTypes,
      canvasHeight: dimensionsTypes,
      ...
   }
   ...
}
```
at `src/index.js:42-56`.

Do you agree with the idea? Is there any underlying behavior for which I _should_ or _must_ use a `number` instead of a `string`? Being a plain and easy change, I can make a PR for you to test it if you feel busy.

Again, thank you very much for your work. I already gave you my star and recommended this tool to my colleagues :slightly_smiling_face:.

Happy coding!

**Comment by embiem** [comment]
Hey @m0Rdk! Thanks, glad that the component works for you 😃 

I agree, string and number should be allowed. If you want, you can submit a PR for this.

**Comment by m0Rdk** [comment]
Hello,

Sorry for the late, I have been on vacation for the last week. This afternoon I am working on the fix, planning to submit the PR for today evening.

Have a good day.

**Comment by audrium** [comment]
Hi, I also need this feature. But I noticed that you forgot to push the latest version to npm (https://www.npmjs.com/package/react-canvas-draw).  1.0.1-hotfix.4 is still the latest one. Can you update it? Cheers

**Comment by embiem** [comment]
Hey @audrium , the latest version does actually include this PR.

Could you please check that you have 1.0.1-hotfix.4 installed?

**Comment by audrium** [comment]
Hi @embiem, yeah, it was my mistake, latest release does include this PR. Everything is working fine, thanks for the nice lib!
