### ISSUE TITLE
Dev dependency has a vulnerability

### ISSUE THREAD

**Issue by rusch95** [embiem/react-canvas-draw#16]
css-loader@0.28.9 depends on macaddress@0.2.8, which has a [arbitrary command injection vuln](https://snyk.io/vuln/SNYK-JS-MACADDRESS-12141
)

You can fix it by updating the major version of css-loader, which I think is on 2.x.x now.

**Comment by embiem** [comment]
Hey, thanks for reporting this. Have update some devDependencies in a new branch, but will still have to test it.

**Comment by embiem** [comment]
This is still pending. There are also more security warnings now. 

I think we should update to the latest nwb version, as well as update as many dependencies as possible without breaking anything.

**Comment by embiem** [comment]
Fixed by #87
