### ISSUE TITLE
Is it possible to get area or coordinates of shape that gets drawn on background image? 

### ISSUE THREAD

**Issue by thug1705** [embiem/react-canvas-draw#21]
Just wondering is there API which provides access to coordinates or area of drawn shape ?

**Comment by embiem** [comment]
Hey!

There's no such API at this moment. The closest you can get to this atm is the [getSaveData()](https://github.com/embiem/react-canvas-draw/blob/develop/src/index.js#L178) function.

**Comment by embiem** [comment]
Hey, I'll close this for now.
