### ISSUE TITLE
Error: ENFILE: file table overflow, open 'node_modules/color-convert/route.js'

### ISSUE THREAD

**Issue by nmassi** [embiem/react-canvas-draw#22]
After instalation I got that error. Someone knows how to fix this?

**Comment by embiem** [comment]
Hey, after a quick Google search I found this: https://github.com/meteor/meteor/issues/8057#issuecomment-261011063

Let me know if this was the issue and whether the solution helped

**Comment by embiem** [comment]
Closing this, let me know if the mentioned reference didn't work.
