### ISSUE TITLE
CaptureStream to Video

### ISSUE THREAD

**Issue by muhdusman** [embiem/react-canvas-draw#24]
Hi,
I have successfully embed the plugin and its working very well
But I want to integrate it with webrtc solutions, for that I need to convert output of canvas to video through capturestream, but I am unable to do that
Any help would be highly appreciated.  Thnx again

**Comment by santosh898** [comment]
for now this module does'nt support capturestream out of the box, because it uses 4 canvas elements stacked up(cursor,drawing,live drawing,background). 
But you can create a hidden canvas and write all 4 canvas data for every `window.requestAnimationFrame(callback)` and stream it.

**Comment by embiem** [comment]
Thanks @santosh898 for answering.
