### ISSUE TITLE
Question: dynamic size based on background image

### ISSUE THREAD

**Issue by chriamue** [embiem/react-canvas-draw#25]
Hi, is it possible to set canvas width and height to background img width and height?
I tried something like that, but the canvas shows only the grid then.
```
componentWillMount() {
    const { backgroundImg } = this.props
      var img = new Image();
    img.onload = () => {
      this.setState({ imgWidth: img.width, imgHeight: img.height, backgroundImg: img.src })
    }
    img.src = backgroundImg
    this.setState({ img })
}
render() {
    const { imgWidth, imgHeight, backgroundImg } = this.state
    if (!backgroundImg || !imgWidth || !imgHeight) {
      return null
    }
        <CanvasDraw
          imgSrc={backgroundImg}
          canvasWidth={imgWidth}
          canvasHeight={imgHeight}
          ref={canvasDraw => (this.saveableCanvas = canvasDraw)}
        />
  }```

**Comment by embiem** [comment]
Hey, yes this should be possible.

From your code example, it looks like you're assigning the Image object itself as `img` in state, but then want to read `imgWidth` etc. from state. Are the `imgWidth`, `imgHeight` and `backgroundImg` props actually defined on the state?

If you could share an example showcasing the issue in a [codesandbox](https://codesandbox.io/), that'd be awesome. Thanks!
