### ISSUE TITLE
Empty package files

### ISSUE THREAD

**Issue by gaelj** [embiem/react-canvas-draw#27]
The package generated at https://registry.npmjs.org/react-canvas-draw/-/react-canvas-draw-1.0.1.tgz, which is used for npm install, is empty (except for LICENSE, package.json and README.md)

**Comment by Bosn** [comment]
Same problem here...  Can't resolve 'react-canvas-draw' in 'xxx' errors occurred.

**Comment by embiem** [comment]
Hey, sorry for this inconvenience. There were issues as I moved the build & publish process to travis. The `1.0.1-hotfix.4` did fix this.

I also just now published a new minor version 1.0.2 (included #23) which should also work. Please make sure to stick with these latest versions, now preferably 1.0.2.
