### ISSUE TITLE
list of lines

### ISSUE THREAD

**Issue by Zeeedark** [embiem/react-canvas-draw#28]
how to get All list lines .I try  get all list lines but the firt time lines every null 
Can i help me
`import React from 'react'
import CanvasDraw from "react-canvas-draw";
import ReactDOM from 'react-dom'
import './paint.scss'

export class PaintComponent extends React.Component {
  state = {
    color: "red",
    width: 80000,
    height: 400,
    brushRadius: 10,
    lazyRadius: 12,
    strData:''
  };
  componentDidMount() {
    let list = ReactDOM.findDOMNode(this.saveableCanvas)
    list.addEventListener('mousedown', this.getData, false)
  }

   getData = async(e) => {
     // if you mousedown
    let list = this.saveableCanvas
    console.log(list,'list have a data ', )
    console.log(list.lines,'but list.lines return [] have a data ', )
  }

 
  render() {
    return (
      <div>
        <div
          style={{
            display: "inline-block",
            width: "24px",
            height: "24px",
            backgroundColor: this.state.color,
            border: "1px solid #272727"
          }}
        />

        {/* this.saveableCanvas.clear()  clear */}
        <button onClick={() => console.log(this.saveableCanvas.getSaveData(),'---'
        )}>
          Save
        </button>
        <CanvasDraw
          ref={canvasDraw => (this.saveableCanvas = canvasDraw)}
          className="paint-wrapper"
          canvasWidth={600}
          canvasHeight={600}
          brushRadius={1}
          lazyRadius={0}
          hideGrid={true}
          brushColor={this.state.color}
          // saveData = {'{"lines":[{"points":[{"x":47.5,"y":102},{"x":47.5,"y":102},{"x":51.5,"y":105},{"x":55.5,"y":116},{"x":61.5,"y":130},{"x":69.5,"y":146},{"x":80.5,"y":164},{"x":91.5,"y":185},{"x":100.5,"y":208},{"x":111.5,"y":233},{"x":120.5,"y":256},{"x":132.5,"y":284},{"x":143.5,"y":307},{"x":150.5,"y":330},{"x":154.5,"y":348},{"x":158.5,"y":361},{"x":162.5,"y":373},{"x":164.5,"y":380},{"x":167.5,"y":384}],"brushColor":"red","brushRadius":1},{"points":[{"x":191.5,"y":81},{"x":191.5,"y":81},{"x":191.5,"y":84},{"x":192.5,"y":89},{"x":200.5,"y":107},{"x":216.5,"y":129},{"x":237.5,"y":159},{"x":265.5,"y":195},{"x":289.5,"y":228},{"x":315.5,"y":263},{"x":337.5,"y":289},{"x":364.5,"y":317},{"x":390.5,"y":344},{"x":416.5,"y":366},{"x":433.5,"y":380}],"brushColor":"red","brushRadius":1},{"points":[{"x":330.5,"y":93},{"x":330.5,"y":93},{"x":345.5,"y":112},{"x":372.5,"y":143},{"x":417.5,"y":188},{"x":465.5,"y":234},{"x":512.5,"y":277},{"x":570.5,"y":321}],"brushColor":"red","brushRadius":1},{"points":[{"x":435.5,"y":69},{"x":435.5,"y":69},{"x":442.5,"y":75},{"x":453.5,"y":85},{"x":463.5,"y":95},{"x":481.5,"y":108},{"x":493.5,"y":119},{"x":505.5,"y":130},{"x":515.5,"y":138},{"x":523.5,"y":146},{"x":530.5,"y":151},{"x":535.5,"y":155},{"x":539.5,"y":158},{"x":542.5,"y":161},{"x":543.5,"y":162},{"x":544.5,"y":164},{"x":546.5,"y":165},{"x":546.5,"y":166}],"brushColor":"red","brushRadius":1},{"points":[{"x":80.5,"y":304},{"x":80.5,"y":304},{"x":89.5,"y":304},{"x":103.5,"y":300},{"x":128.5,"y":292},{"x":156.5,"y":279},{"x":195.5,"y":262},{"x":231.5,"y":247},{"x":265.5,"y":233},{"x":304.5,"y":217},{"x":336.5,"y":199},{"x":372.5,"y":186},{"x":408.5,"y":170},{"x":448.5,"y":151},{"x":483.5,"y":139},{"x":522.5,"y":122},{"x":533.5,"y":116},{"x":564.5,"y":103},{"x":596.5,"y":92}],"brushColor":"red","brushRadius":1},{"points":[{"x":111.5,"y":339},{"x":111.5,"y":339},{"x":121.5,"y":336},{"x":137.5,"y":330},{"x":152.5,"y":327},{"x":175.5,"y":318},{"x":198.5,"y":307},{"x":229.5,"y":295},{"x":258.5,"y":282},{"x":288.5,"y":272},{"x":326.5,"y":261},{"x":353.5,"y":255},{"x":385.5,"y":246},{"x":418.5,"y":236},{"x":453.5,"y":227},{"x":479.5,"y":221},{"x":511.5,"y":214},{"x":542.5,"y":211},{"x":562.5,"y":210},{"x":586.5,"y":203}],"brushColor":"red","brushRadius":1}],"width":600,"height":600}'}
        />
      </div >

    )
  }
}

export default PaintComponent`

**Comment by embiem** [comment]
Hey, first it'd be great if you create an example in codesandbox. I quickly copied your example code into one: https://codesandbox.io/embed/react-canvas-draw-example-ndq5d

If I understand you correctly, you're wondering why in the mousedown event handler, when console logging `list.lines` it shows an empty array and just logging `list` shows actual entries in the `lines` array, once you expand the object in the console.

1. The array is actually empty on first call, as the `mousedown` event will be fired before any line could be drawn.
2. Once you expand the component's object in the inspector, it will show you the current state of references like the `lines` array. If you expand the array as well, it should show the same content. This is because the browser's console will show you then the current state of the array.

Sorry, maybe not the best explanation. If that wasn't at all the issue you're facing, please let me know.
