### ISSUE TITLE
Question/Suggestion: check if CanvasDraw has been drawed on

### ISSUE THREAD

**Issue by b5imply** [embiem/react-canvas-draw#3]
Are there any support, or suggestion for some function to know if a canvas has been drawed on or not. I noticed in the code there is an array to store lines. Maybe if a boolean is returned if the linesArray is empty. 

I'm questioning because I want to use this canvas in my forms, and want to validate. I figure that only thing we want to validate is when a drawing is required, hence we need some bool if the canvas has been drawed on.

**Comment by mBeierl** [comment]
Hey!

2 approaches here:

1. You could use the prop "onChange", which is a function that is called every time the user draws in the canvas
2. Get a ref ([example](https://github.com/mBeierl/react-canvas-draw/blob/master/demo/src/index.js#L104)) and then check on the reference whether `canvasRef.linesArray.length > 0`

Hope this helps.
