### ISSUE TITLE
Preventing scrolling 

### ISSUE THREAD

**Issue by aoelbaum** [embiem/react-canvas-draw#34]
Thank you for this awesome library! I have noticed that if your page has horizontal or vertical scrolling then using touch input on the canvas for mobile devices makes it very difficult to draw. Have you thought about preventing scrolling on the document.body if the target of the touch event is the canvas?

(Side note: I appreciate the undo method, but have you also thought about implementing an eraser prop?) Thank you again!

**Comment by embiem** [comment]
Thanks!

I've added a new issue to track the eraser mode you suggested.

Regarding the scrolling issue: I'm having trouble to reproduce this. When I start drawing then the page does not scroll.

Which browser and device do you experience this issue on?

**Comment by aoelbaum** [comment]
> Thanks!
> 
> I've added a new issue to track the eraser mode you suggested.
> 
> Regarding the scrolling issue: I'm having trouble to reproduce this. When I start drawing then the page does not scroll.
> 
> Which browser and device do you experience this issue on?

So I just tested on my iPhone again and it seems that I can’t reproduce the issue either. Perhaps, the issue has been fixed or back when I had tested the canvas, it was an issue of size and not the canvas itself. Either way, it looks good and you can close this issue. Also, thanks for adding my eraser suggestion as a new issue!
