### ISSUE TITLE
how to get canvas data as base64?

### ISSUE THREAD

**Issue by Ivanrputra** [embiem/react-canvas-draw#35]

**Comment by jessicaanhdao** [comment]
I would love to know this too

**Comment by jessicaanhdao** [comment]
So what I did was
have ` images : [] ` in state
then called a function that gets binary from canvas tag. If you check from Inspect, there are 4 canvases, one of them is our drawing, one is the white canvas, one is the brush and one is something else. The second canvas is where our drawing is.
```
let canvas = document.getElementsByTagName('canvas');
    console.log(canvas)
    let localImages = []
    for(let c of canvas) {
      localImages.push(c.toDataURL())
    }
    this.setState({
      images : localImages
    })
```
then in `render()`
```
<img src={this.state.images[1]}/>
```

**Comment by Ivanrputra** [comment]
thanks, this help me a lot
hope this will work on my project
