### ISSUE TITLE
Question: How to  know when  loadSaveData ends the live  drawing?

### ISSUE THREAD

**Issue by iknox27** [embiem/react-canvas-draw#37]
Hi @embiem I tried approach number 1 from here https://github.com/embiem/react-canvas-draw/issues/3  but didn't received any log. Is there a way  to  know when  loadSaveData ends the live  drawing ?

**Comment by embiem** [comment]
Hi and thanks for your question. Currently it's not possible to know when `loadSaveData` ends the live drawing.

I suggest we add a callback prop like `onLoadEnd`, which gets called after the initial load of a saved drawing is finished.
Would this solve your issue?

**Comment by ksocha** [comment]
I have a similar issue. I'm currently trying to sync canvas data between multiple users (each of them has to be able to draw).
I've tried to make use of `onChange` prop to get the data from currently drawing user and propagate it to other users. After receiving the data, others would call `loadSaveData` to apply it to their canvases. Problem is that after calling `loadSaveData`, `onChange` callback is called too causing infinite loop of synchronising. I really could make a use of additional callback that would be called only once after the user ends interacting with the canvas.

**Comment by embiem** [comment]
Seems to be related to #93, where we track this issue right now.
