### ISSUE TITLE
Question: any way to receive events from the canvas draw and pass out the updated object?

### ISSUE THREAD

**Issue by mp2468** [embiem/react-canvas-draw#39]
I'm noticing that all of the events that happen inside are blocked with event.stopPropagation but in this case I am trying to get an event emitted every time new draw happens (in order to convert it to b64 and save it in my state). Not sure if relevant to this but the reason I'm doing that is because in the event of a window resize, the image inside the canvas disappears and I'd like to be able to re-set it back there from the saved b64 with the drawing preserved.

Currently I'm just making the size of the canvas static in order to prevent that resize from happening ever but I don't consider that an optimal solution. Is there any other way I should deal with this?

**Comment by embiem** [comment]
Hey! Thanks for sharing your use case.

What I understand is, that you need an `onChange` event which you can pass to the CanvasDraw component and gets called every time something is drawn. Is this correct?

**Comment by dyarfaradj** [comment]
> Hey! Thanks for sharing your use case.
> 
> What I understand is, that you need an `onChange` event which you can pass to the CanvasDraw component and gets called every time something is drawn. Is this correct?

Yeah, a onChange is definitely needed. I hope you can add that

**Comment by mp2468** [comment]
Yes, that's exactly what I'm looking for @embiem. I want to save and export it in b64 format each time a new draw event is emitted.

**Comment by oyeanuj** [comment]
@embiem Great library! I think I might have a related use-case (let me know if you'd like me to create a different issue if this is not related).

I'm trying to get the location where the mouse is being first clicked to drop icons/emojis on top. Essentially, instead of free form drawing, users can tap on different parts and different emojis will appear there on the canvas. So, to make that happen it seems like I'd need an `onChange` that tells me the location and an ability to drop something on the canvas myself?

**Comment by dyarfaradj** [comment]
> @embiem Great library! I think I might have a related use-case (let me know if you'd like me to create a different issue if this is not related).
> 
> I'm trying to get the location where the mouse is being first clicked to drop icons/emojis on top. Essentially, instead of free form drawing, users can tap on different parts and different emojis will appear there on the canvas. So, to make that happen it seems like I'd need an `onChange` that tells me the location and an ability to drop something on the canvas myself?

owner seems inactive, you can use this https://github.com/sowcow/react-canvas-draw instead, it's a fork but with onChange implementation 

@embiem You can merge this PR #50 it adds onChange

**Comment by embiem** [comment]
@dyarfaradj thanks for the PR to add an onChange prop, I'll merge and release new version asap.

@oyeanuj your use case is more specific than free form drawing, which is currently the focus of this component. You could fork this component and modify it to your needs.

The only way I'd see this functionality as part of react-canvas-draw, is if we introduce some kind of brush system to modify what is drawn. I've outlined a feature request in #53.
