### ISSUE TITLE
Can't draw dots

### ISSUE THREAD

**Issue by AnaghaThekkedath** [embiem/react-canvas-draw#42]
The canvas doesn't handle on click, so when you need to make dots you have to click and drag minutely.
Thank you.

Also is it possible to give style to the background image?

**Comment by embiem** [comment]
Thanks for reporting.

Currently, it is only possible to set an image as background in the canvas using the `imgSrc` prop.

**Comment by embiem** [comment]
This is now fixed, will be released in the next version (1.1.1)
