### ISSUE TITLE
Add feature to export final canvas to png or base64

### ISSUE THREAD

**Issue by embiem** [embiem/react-canvas-draw#43]
As e.g. #36, #35, #11 show, it's a common use case to export final canvas to png or base64 using the toDataUrl() function. We want to support an easy and documented way to do this for this component.

Here is an example of how it can be done today: https://codesandbox.io/s/ko956o59or
`canvasRef.current.canvasContainer.children[1].toDataURL()`

My proposal is to have a proxy on the component, so that we can simply call `canvasRef.current.toDataURL()`.

**Comment by embiem** [comment]
Additionally, in #62 there's the need to save the drawing together with the background image into a new image. When implementing the feature described here, one should take this case into account as well.

**Comment by TheAlemazing** [comment]
Any updates?

**Comment by s-kris** [comment]
Any updates? Thanks

**Comment by embiem** [comment]
Sorry, just saw that I'm assigned. This ticket is up for grabs. I currently have not the time to work on this.

If you plan on working on this, please write a short notice here so others know.

**Comment by embiem** [comment]
Referencing pending PR #67 here, which tries to implement this.

**Comment by sleepypikachu** [comment]
@embiem no action in some time on PR #67 so I'm going to pick this up if you don't object :-)

**Comment by clemkofi** [comment]
Nice @sleepypikachu ...... please any updates yet?

**Comment by sleepypikachu** [comment]
I did a hack for now so moved on. If @embiem can clarify what he wants the API to look like I am happy to implement...

**Comment by shamseertk** [comment]
### REACTJS : I did this for background image export. Hope this helps
    const d = this.saveableCanvas.canvasContainer.children[1].toDataURL();
    const w = window.open('about:blank', 'image from canvas');
    const img = require("relativepath to background image");
    w.document.write("<img src='"+d+"' style='background-image: url( " + img + "); background-size: contain' alt='Exporting'/>");

**Comment by darshanksexathought** [comment]
Any Updates?

**Comment by franciscoandres** [comment]
Any updates?

**Comment by jng27** [comment]
For anyone looking for ways to download this, this works for me.

let imageURL = this.refs.saveableCanvas.canvasContainer.childNodes[1].toDataURL()
let downloadBtnRef = document.getElementById("downloadLink")
downloadBtnRef.href = imageURL

**Comment by embiem** [comment]
Please, go ahead.

**Comment by sleepypikachu** [comment]
> Please, go ahead.
>

**Comment by fsolarv22** [comment]
To create a Base64 image you can do this:

`const canvasRef= useRef(null)
const image = canvasRef.current.canvasContainer.childNodes[1].toDataURL()

return <CanvasDraw ref={canvasRef} ...props />
`

**Comment by UmerMIB** [comment]
> To create a Base64 image you can do this:
> 
> const canvasRef= useRef(null)
> const image = canvasRef.current.canvasContainer.childNodes[1].toDataURL()
> 
> return <CanvasDraw ref={canvasRef} ...props />

Can you please tell me your version?

**Comment by UmerMIB** [comment]
> To create a Base64 image you can do this:
> 
> const canvasRef= useRef(null)
> const image = canvasRef.current.canvasContainer.childNodes[1].toDataURL()
> 
> return <CanvasDraw ref={canvasRef} ...props />

By this I cannot get the background image just getting only canvas

**Comment by JGP84** [comment]
> ### REACTJS : I did this for background image export. Hope this helps, But this wont export as single image, it will still be a bkg img.
> ```
> const d = this.saveableCanvas.canvasContainer.children[1].toDataURL();
> const w = window.open('about:blank', 'image from canvas');
> const img = require("relativepath to background image");
> w.document.write("<img src='"+d+"' style='background-image: url( " + img + "); background-size: contain' alt='Exporting'/>");
> ```

Thank you very much!

**Comment by embiem** [comment]
FYI a new function has now been added that can be used to get the data url: `getDataURL(fileType, useBgImage, backgroundColour)`

**Comment by wondem12** [comment]
any solution to get the canvas and the background-image combined ? `getDataURL(fileType, useBgImage, backgroundColour)` doesn't work

**Comment by bee-mcc** [comment]
@wondem12 @embiem did you ever make any progress here? I would love to use the new feature to save the drawing in a canvas + the background image as one new PNG, but so far I have been playing with the newly document function ```getDataURL(fileType, useBgImage, backgroundColour)``` and it doesn't seem to work for me.

**Comment by bee-mcc** [comment]
Here's what I'm doing, to no avail. It saves the drawing, but not the background image

```
    const canvasRef = useRef(null);
    const [drawing, setDrawing] = useState();

    useEffect(() => {
        }, [props.URL]);

    function saveData() {
        console.log("hello")
        const base64 = canvasRef.current.getDataURL(".png", true, "grey")
        const points = canvasRef.current.getSaveData()
        setDrawing(base64)
        console.log(base64)
        console.log(points)

    }
```
