### ISSUE TITLE
imgSrc not rendered!

### ISSUE THREAD

**Issue by anil32** [embiem/react-canvas-draw#61]
at first image , there is no problem but if you try to select another image ant set it with setState,  imgSrc not rendered

**Comment by easyselva** [comment]
> at first image , there is no problem but if you try to select another image ant set it with setState, imgSrc not rendered

Me to have same problem. Any solution?

**Comment by easyselva** [comment]
after changing src  please do this  this.saveableCanvas.drawImage();

**Comment by sjzamora86** [comment]
Thanks @easyselva it works for me! :D

**Comment by embiem** [comment]
Actually, reopening to track as an issue. The component should detect the changed image src and update accordingly.

**Comment by NishantTadvi** [comment]
Also Image is overlapping each other
![image](https://user-images.githubusercontent.com/52619777/79588043-035b2500-80f1-11ea-98c8-6c3cd0b16841.png)

**Comment by embiem** [comment]
PR to fix this is in the works at #76

**Comment by JustinTheeDude** [comment]
Is there a way to call an image in the imgSrc prop locally instead of using a hosted image?

**Comment by parammittal16** [comment]
@NishantTadvi A working but not the very best fix is to call this.saveableCanvas.drawImage(); as well as alter canvas width or height a little bit through state, this will force canvas to re-render and will be rendering new image without previous image overlapping. Hope this helps !!

**Comment by akshatbhargava123** [comment]
I'm receiving CORS error for all the images I tried, the possible reason is that the library tries to fetch image using `XMLHttpRequest` or `fetch` or some other programmatic method.

**Comment by ShahNafis** [comment]
I am also getting the same CORS error with some images. For example, an image of a dog like [this](https://s3.amazonaws.com/cdn-origin-etr.akc.org/wp-content/uploads/2019/12/03202400/Yellow-Labrador-Retriever.jpg) one doesn't work and gives the following error.

![image](https://user-images.githubusercontent.com/29672994/103177664-6be6ce00-484a-11eb-96fa-a4a79f7f6305.png)

**Comment by embiem** [comment]
#76 is now merged which fixes this issue
