### ISSUE TITLE
Using saveData without animation

### ISSUE THREAD

**Issue by foucdeg** [embiem/react-canvas-draw#69]
I'm trying to rerender a previous drawing using the `saveData` prop.

Using this prop it seems that the drawing has to be animated, whereas the `loadSaveData()` accepts a second argument to disable animation.

Is there any way to disable drawing animation when using the `saveData` prop ?

**Comment by alexfruehwirth** [comment]
@foucdeg set `loadTimeOffser={0}` as a prop. This should solve your issue!

**Comment by salehy1981** [comment]
immediateLoading={true}

**Comment by embiem** [comment]
Thanks! Both above mentioned solutions should work. 

This is definitely an API that would need some rethinking for a v2, as it is not very clear how to achieve it, and it's actually achievable using these two mentioned methods. So, thanks for asking the question!

Closing for now, please let me know if you have any further issues with this.
