### ISSUE TITLE
Tainted canvas

### ISSUE THREAD

**Issue by Drarig29** [embiem/react-canvas-draw#70]
I tried the solution given [here](https://github.com/embiem/react-canvas-draw/issues/62#issuecomment-599714872), but I have this error:

> SecurityError: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.

I found a [solution](https://thisinterestsme.com/tainted-canvases/), you'd only have one line just after this one:
https://github.com/embiem/react-canvas-draw/blob/de4ec18601f769efa8b11b9e6ac5d86b23beb117/src/index.js#L168

You'd need to add:
```javascript
this.image.origin =  "anonymous";
```

**Comment by embiem** [comment]
Thanks! I just pushed the fix using the `crossOrigin` API.
