### ISSUE TITLE
How I can use the CLEAR function?

### ISSUE THREAD

**Issue by Maark007** [embiem/react-canvas-draw#72]
Well I tried these way:
``
    <div>
            <CanvasDraw
              brushColor='#000'
              lazyRadius='0'
              brushRadius='3'
              canvasWidth={400}
              canvasHeight={200}
              styled={{ marginLeft: 10, marginRight: 10 }}
              Ref={1}
            >
            </CanvasDraw>
            <button onClick={() => this.saveableCanvas.clear()}>Clear</button>
          </div>
``  
Where the saveableCanvas come from?

**Comment by NishantTadvi** [comment]
```
<div> 
<CanvasDraw 
   brushColor='#000' 
   lazyRadius='0' 
   brushRadius='3' 
   canvasWidth={400} 
   canvasHeight={200} 
   style={{ marginLeft: 10, marginRight: 10 }}
   ref={canvasDraw => (this.saveableCanvas= canvasDraw)}
>
</CanvasDraw>
<button onClick={() => this.saveableCanvas.clear()}>Clear</button> </div>
```

**Comment by Maark007** [comment]
@NishantTadvi  Didn't work.

**Comment by Maark007** [comment]
Well, work with useRef().

**Comment by parammittal16** [comment]
@Maark007 can you tell me how you user useRef here ? Thanks :)
