### ISSUE TITLE
`onChange` triggers

### ISSUE THREAD

**Issue by martin056** [embiem/react-canvas-draw#81]
* Calling `clear()` doesn't trigger `onChange`
* Calling `undo()` triggers `onChange` several (equal to the remaining lines) times

If the above points are not intentional, I can make a PR and fix them :)

**Comment by ziaongit** [comment]
I did it like bellow for clear.
```
 const handleOnchange = () => {
  // This will work for clear
  };
<CanvasDraw
 onChange={handleOnchange}
>
```

**Comment by embiem** [comment]
Should be the same issue as described in #93, so I'll close this and track the issue in 93.
