### ISSUE TITLE
Transparent canvas?

### ISSUE THREAD

**Issue by corysimmons** [embiem/react-canvas-draw#95]
Would love to draw on people's faces.

**Comment by corysimmons** [comment]
![image](https://user-images.githubusercontent.com/224636/89081128-ab22f880-d358-11ea-8377-55a4ce125aed.png)

For some reason it wraps the canvas in that div with bg white. Kinda curious why 4 canvas, but more worried about bg.

**Comment by pburtchaell** [comment]
The solution is:

```
<CanvasDraw style={{ background: "none" }} />
```

**Comment by corysimmons** [comment]
Thank you! I am happy now!

![image](https://user-images.githubusercontent.com/224636/90434424-5e9b2500-e09b-11ea-900b-dfe6479a8257.png)
